# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='日期')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='报障时间')),
                ('department', models.CharField(blank=True, max_length=64, null=True, verbose_name='报障部门')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='报障内容')),
                ('handler', models.CharField(blank=True, max_length=64, null=True, verbose_name='处理人')),
                ('result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
            ],
            options={
                'db_table': 'journal',
            },
        ),
    ]
