# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=64, verbose_name='位置')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='报障时间')),
                ('department', models.CharField(blank=True, max_length=64, null=True, verbose_name='报障部门')),
                ('people', models.CharField(blank=True, max_length=64, null=True, verbose_name='报障人')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='报障内容')),
                ('handler', models.CharField(blank=True, max_length=64, null=True, verbose_name='处理人')),
                ('result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('status', models.IntegerField(blank=True, choices=[(1, '处理中'), (2, '处理完成')], default=1, null=True, verbose_name='处理状态')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='处理结束时间')),
                ('sign', models.CharField(blank=True, max_length=64, null=True, verbose_name='主管签名')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='主管备注')),
            ],
            options={
                'db_table': 'journal',
                'default_permissions': (),
                'permissions': (('approve', '审批'),),
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='标题')),
            ],
            options={
                'db_table': 'sheet',
                'default_permissions': (),
                'permissions': (('view_sheet', '查看表格'), ('edit_sheet', '管理表格')),
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='query.Sheet', verbose_name='所属表格'),
        ),
    ]
