# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='标题')),
            ],
            options={
                'db_table': 'sheet',
                'default_permissions': (),
                'permissions': (('view_sheet', '查看表格'), ('edit_sheet', '管理表格')),
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='主管备注'),
        ),
        migrations.AddField(
            model_name='journal',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='处理结束时间'),
        ),
        migrations.AddField(
            model_name='journal',
            name='people',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='报障人'),
        ),
        migrations.AddField(
            model_name='journal',
            name='sign',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主管签名'),
        ),
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '处理中'), (2, '处理完成')], default=1, null=True, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='报障时间'),
        ),
        migrations.AlterModelTable(
            name='journal',
            table='test',
        ),
    ]
