# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-29 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20170729_0530'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journal',
            table='journal',
        ),
    ]
