# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-30 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20170729_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='position',
            field=models.CharField(default='', max_length=64, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='journal',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.Sheet', verbose_name='所属表格'),
        ),
    ]
