# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20170730_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
    ]
