# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20170806_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='query.Sheet', verbose_name='所属表格'),
        ),
    ]
