# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-13 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20170812_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'default_permissions': (), 'permissions': (('approve', '审批'),)},
        ),
    ]
